enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
enabled = true
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
excluded-patches = "'Hide Shorts components' 'Theme' 'Change header' 'Custom branding'"

[YT-Music]
enabled = true
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "arm64-v8a"

[GooglePhotos]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
arch = "arm64-v8a"

[Reddit]
enabled = true
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
arch = "arm64-v8a"

[Tiktok]
enabled = true
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
# uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
included-patches = "'SIM spoof'"

[Twitch]
enabled = true
# apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
arch = "arm64-v8a"

[Spotify]
enabled = true
archive-dlurl = "https://archive.org/download/e85-apks/apks/com.spotify.music"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
